"""Shared state schema for the LangGraph agent pipeline.

Defines the dataclasses and TypedDict that flow through every agent
node in the graph. Each agent reads from and writes to this state,
ensuring a consistent data contract across the entire cycle.
"""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Any, TypedDict


@dataclass
class Signal:
    """Aggregated prediction signal for a single trading pair.

    Combines the LSTM price forecast and FinBERT sentiment score
    into a unified signal that the Manager Agent uses to rank coins.
    """

    symbol: str
    """Trading pair (e.g. ``BTC/USDT``)."""

    predicted_return: float
    """Raw model output interpreted as next-period return (e.g. 0.02 = 2%)."""

    direction: str
    """Predicted price direction — ``"up"``, ``"down"``, or ``"neutral"``."""

    confidence: float
    """Model confidence in the prediction, scaled 0–1."""

    sentiment_score: float
    """Aggregated sentiment composite score (positive - negative), range -1 to +1."""

    sentiment_label: str
    """Dominant sentiment label — ``"positive"``, ``"negative"``, or ``"neutral"``."""

    fear_greed_value: int
    """Fear & Greed Index value (0–100)."""

    timestamp: datetime
    """When this signal was generated (UTC)."""

    vol_regime: int = 0
    """Volatility regime — ``0`` (low) or ``1`` (high). Defaults to low."""


@dataclass
class ProposedTrade:
    """A trade proposal generated by the Manager Agent.

    Must pass Risk Agent screening before it becomes an order.
    """

    symbol: str
    """Trading pair to trade."""

    side: str
    """Order side — ``"BUY"`` or ``"SELL"``."""

    quantity: Decimal
    """Amount of base asset to trade."""

    entry_price: Decimal
    """Expected entry price for the trade."""

    stop_loss_price: Decimal
    """Stop-loss price level."""

    take_profit_price: Decimal
    """Take-profit price level."""

    signal_confidence: float
    """Confidence score from the originating signal (0–1)."""

    reasoning: str
    """Human-readable explanation for why this trade is proposed."""


@dataclass
class ExecutedTrade:
    """Record of a fully executed order returned by the Execution Agent."""

    proposal: ProposedTrade
    """The original trade proposal that was executed."""

    executed_price: Decimal
    """Actual fill price from the exchange."""

    executed_quantity: Decimal
    """Actual filled quantity (may differ from proposal due to slippage)."""

    order_id: str
    """Exchange-assigned order identifier."""

    status: str
    """Order status — ``"FILLED"``, ``"PARTIALLY_FILLED"``, or ``"FAILED"``."""

    timestamp: datetime
    """When the order was executed (UTC)."""

    pnl: Decimal
    """Realised profit / loss for this trade (zero until closed)."""


class AgentState(TypedDict):
    """Shared state that flows through every node in the LangGraph pipeline.

    All agents read from and write to this dict. Fields are populated
    incrementally as the cycle progresses.
    """

    cycle_id: str
    """Unique identifier for the current trading cycle (e.g. UUID)."""

    timestamp: datetime
    """When the current cycle started (UTC)."""

    pipeline_data: dict[str, Any]
    """Raw output from ``DataPipeline.run()`` keyed by pair."""

    signals: list[Signal]
    """Combined price + sentiment signals for each pair, ranked by strength."""

    proposed_trades: list[ProposedTrade]
    """Trades generated by the Manager Agent awaiting risk screening."""

    approved_trades: list[ProposedTrade]
    """Trades that passed Risk Agent screening, ready for execution."""

    executed_trades: list[ExecutedTrade]
    """Trades that have been routed to the exchange and filled."""

    portfolio_summary: dict[str, Any]
    """Current portfolio state — balances, total value, P&L per position."""

    risk_report: dict[str, Any]
    """Risk metrics for the current cycle — VaR, max drawdown, exposure."""

    cycle_log: list[str]
    """Timestamped log messages recording each step of the cycle."""
